services:
  bookstore:
    image: projectcv:1.0.0
    restart: unless-stopped
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell < createsuperuser.py &&
             python manage.py runserver 0.0.0.0:6030"
    container_name: projectcv
    ports:
      - 0.0.0.0:6030:6030
    depends_on:
      - db


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: